/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AxleState_H_
#define	_AxleState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AxleLocation.h"
#include "AxleWeight.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AxleState */
typedef struct AxleState {
	AxleLocation_t	*location	/* OPTIONAL */;
	AxleWeight_t	*weight	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AxleState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AxleState;

#ifdef __cplusplus
}
#endif

#endif	/* _AxleState_H_ */
