/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ITIScodesAndTextChoice_H_
#define	_ITIScodesAndTextChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ITIScodes.h"
#include "ITIStext.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITIScodesAndTextChoice__item_PR {
	ITIScodesAndTextChoice__item_PR_NOTHING,	/* No components present */
	ITIScodesAndTextChoice__item_PR_itis,
	ITIScodesAndTextChoice__item_PR_text
} ITIScodesAndTextChoice__item_PR;

/* ITIScodesAndTextChoice */
typedef struct ITIScodesAndTextChoice {
	struct ITIScodesAndTextChoice__item {
		ITIScodesAndTextChoice__item_PR present;
		union ITIScodesAndTextChoice__item_u {
			ITIScodes_t	 itis;
			ITIStext_t	 text;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} item;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITIScodesAndTextChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITIScodesAndTextChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _ITIScodesAndTextChoice_H_ */
