/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PreemptState_H_
#define	_PreemptState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PreemptState {
	PreemptState_none	= 0,
	PreemptState_other	= 1,
	PreemptState_notActive	= 2,
	PreemptState_notActiveWithCall	= 3,
	PreemptState_entryStarted	= 4,
	PreemptState_trackService	= 5,
	PreemptState_dwell	= 6,
	PreemptState_linkActive	= 7,
	PreemptState_existStarted	= 8,
	PreemptState_maximumPresence	= 9,
	PreemptState_ackowledgedButOverridden	= 10
	/*
	 * Enumeration is extensible
	 */
} e_PreemptState;

/* PreemptState */
typedef ENUMERATED_t	 PreemptState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PreemptState;
asn_struct_free_f PreemptState_free;
asn_struct_print_f PreemptState_print;
asn_constr_check_f PreemptState_constraint;
ber_type_decoder_f PreemptState_decode_ber;
der_type_encoder_f PreemptState_encode_der;
xer_type_decoder_f PreemptState_decode_xer;
xer_type_encoder_f PreemptState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PreemptState_H_ */
