/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SteeringWheelAngleRateOfChange_H_
#define	_SteeringWheelAngleRateOfChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SteeringWheelAngleRateOfChange */
typedef long	 SteeringWheelAngleRateOfChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SteeringWheelAngleRateOfChange;
asn_struct_free_f SteeringWheelAngleRateOfChange_free;
asn_struct_print_f SteeringWheelAngleRateOfChange_print;
asn_constr_check_f SteeringWheelAngleRateOfChange_constraint;
ber_type_decoder_f SteeringWheelAngleRateOfChange_decode_ber;
der_type_encoder_f SteeringWheelAngleRateOfChange_encode_der;
xer_type_decoder_f SteeringWheelAngleRateOfChange_decode_xer;
xer_type_encoder_f SteeringWheelAngleRateOfChange_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SteeringWheelAngleRateOfChange_H_ */
