/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SteeringAxleLubePressure_H_
#define	_SteeringAxleLubePressure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SteeringAxleLubePressure */
typedef long	 SteeringAxleLubePressure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SteeringAxleLubePressure;
asn_struct_free_f SteeringAxleLubePressure_free;
asn_struct_print_f SteeringAxleLubePressure_print;
asn_constr_check_f SteeringAxleLubePressure_constraint;
ber_type_decoder_f SteeringAxleLubePressure_decode_ber;
der_type_encoder_f SteeringAxleLubePressure_encode_der;
xer_type_decoder_f SteeringAxleLubePressure_decode_xer;
xer_type_encoder_f SteeringAxleLubePressure_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SteeringAxleLubePressure_H_ */
