/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TermTime_H_
#define	_TermTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TermTime */
typedef long	 TermTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TermTime;
asn_struct_free_f TermTime_free;
asn_struct_print_f TermTime_print;
asn_constr_check_f TermTime_constraint;
ber_type_decoder_f TermTime_decode_ber;
der_type_encoder_f TermTime_encode_der;
xer_type_decoder_f TermTime_decode_xer;
xer_type_encoder_f TermTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TermTime_H_ */
