/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TireLocation_H_
#define	_TireLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TireLocation */
typedef long	 TireLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TireLocation;
asn_struct_free_f TireLocation_free;
asn_struct_print_f TireLocation_print;
asn_constr_check_f TireLocation_constraint;
ber_type_decoder_f TireLocation_decode_ber;
der_type_encoder_f TireLocation_encode_der;
xer_type_decoder_f TireLocation_decode_xer;
xer_type_encoder_f TireLocation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TireLocation_H_ */
