/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TireState_H_
#define	_TireState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TireLocation.h"
#include "TirePressure.h"
#include "TireTemp.h"
#include "WheelSensorStatus.h"
#include "WheelEndElectFault.h"
#include "TireLeakageRate.h"
#include "TirePressureThresholdDetection.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TireState */
typedef struct TireState {
	TireLocation_t	*location	/* OPTIONAL */;
	TirePressure_t	*pressure	/* OPTIONAL */;
	TireTemp_t	*temp	/* OPTIONAL */;
	WheelSensorStatus_t	*wheelSensorStatus	/* OPTIONAL */;
	WheelEndElectFault_t	*wheelEndElectFault	/* OPTIONAL */;
	TireLeakageRate_t	*leakageRate	/* OPTIONAL */;
	TirePressureThresholdDetection_t	*detection	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TireState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TireState;

#ifdef __cplusplus
}
#endif

#endif	/* _TireState_H_ */
