/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_VehicleSafetyExtension_H_
#define	_VehicleSafetyExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EventFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathHistory;
struct PathPrediction;
struct RTCMPackage;

/* VehicleSafetyExtension */
typedef struct VehicleSafetyExtension {
	EventFlags_t	*events	/* OPTIONAL */;
	struct PathHistory	*pathHistory	/* OPTIONAL */;
	struct PathPrediction	*pathPrediction	/* OPTIONAL */;
	struct RTCMPackage	*theRTCM	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSafetyExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSafetyExtension;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PathHistory.h"
#include "PathPrediction.h"
#include "RTCMPackage.h"

#endif	/* _VehicleSafetyExtension_H_ */
