/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ZoneState_H_
#define	_ZoneState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneWidth.h"
#include "NodeList.h"
#include "LaneNumber.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ZoneState */
typedef struct ZoneState {
	struct ZoneState__enclosed {
		A_SEQUENCE_OF(LaneNumber_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *enclosed;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	NodeList_t	 nodeList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ZoneState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ZoneState;

#ifdef __cplusplus
}
#endif

#endif	/* _ZoneState_H_ */
