/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "AllInclusive.h"

static asn_TYPE_member_t asn_MBR_AllInclusive_1[] = {
	{ ATF_POINTER, 237, offsetof(struct AllInclusive, item6_1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccelerationSet4Way,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-1"
		},
	{ ATF_POINTER, 236, offsetof(struct AllInclusive, item6_2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccelSteerYawRateConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-2"
		},
	{ ATF_POINTER, 235, offsetof(struct AllInclusive, item6_4),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaOffsetSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-4"
		},
	{ ATF_POINTER, 234, offsetof(struct AllInclusive, item6_5),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Approach,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-5"
		},
	{ ATF_POINTER, 233, offsetof(struct AllInclusive, item6_6),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApproachObject,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-6"
		},
	{ ATF_POINTER, 232, offsetof(struct AllInclusive, item6_7),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BarrierLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-7"
		},
	{ ATF_POINTER, 231, offsetof(struct AllInclusive, item6_8),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BrakeSystemStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-8"
		},
	{ ATF_POINTER, 230, offsetof(struct AllInclusive, item6_9),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSMblob,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-9"
		},
	{ ATF_POINTER, 229, offsetof(struct AllInclusive, item6_10),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BumperHeights,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-10"
		},
	{ ATF_POINTER, 228, offsetof(struct AllInclusive, item6_11),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Circle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-11"
		},
	{ ATF_POINTER, 227, offsetof(struct AllInclusive, item6_12),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConfidenceSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-12"
		},
	{ ATF_POINTER, 226, offsetof(struct AllInclusive, item6_13),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConnectsTo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-13"
		},
	{ ATF_POINTER, 225, offsetof(struct AllInclusive, item6_14),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CrosswalkLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-14"
		},
	{ ATF_POINTER, 224, offsetof(struct AllInclusive, item6_15),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-15"
		},
	{ ATF_POINTER, 223, offsetof(struct AllInclusive, item6_16),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-16"
		},
	{ ATF_POINTER, 222, offsetof(struct AllInclusive, item6_17),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-17"
		},
	{ ATF_POINTER, 221, offsetof(struct AllInclusive, item6_18),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-18"
		},
	{ ATF_POINTER, 220, offsetof(struct AllInclusive, item6_19),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DMonthDay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-19"
		},
	{ ATF_POINTER, 219, offsetof(struct AllInclusive, item6_20),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-20"
		},
	{ ATF_POINTER, 218, offsetof(struct AllInclusive, item6_21),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DYearMonth,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-21"
		},
	{ ATF_POINTER, 217, offsetof(struct AllInclusive, item6_22),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FullPositionVector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-22"
		},
	{ ATF_POINTER, 216, offsetof(struct AllInclusive, item6_23),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Intersection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-23"
		},
	{ ATF_POINTER, 215, offsetof(struct AllInclusive, item6_24),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-24"
		},
	{ ATF_POINTER, 214, offsetof(struct AllInclusive, item6_25),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExitService,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-25"
		},
	{ ATF_POINTER, 213, offsetof(struct AllInclusive, item6_26),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GenericSignage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-26"
		},
	{ ATF_POINTER, 212, offsetof(struct AllInclusive, item6_27),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedLimit,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-27"
		},
	{ ATF_POINTER, 211, offsetof(struct AllInclusive, item6_28),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WorkZone,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-28"
		},
	{ ATF_POINTER, 210, offsetof(struct AllInclusive, item6_29),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_J1939data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-29"
		},
	{ ATF_POINTER, 209, offsetof(struct AllInclusive, item6_30),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MovementState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-30"
		},
	{ ATF_POINTER, 208, offsetof(struct AllInclusive, item6_31),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-31"
		},
	{ ATF_POINTER, 207, offsetof(struct AllInclusive, item6_32),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Offsets,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-32"
		},
	{ ATF_POINTER, 206, offsetof(struct AllInclusive, item6_33),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-33"
		},
	{ ATF_POINTER, 205, offsetof(struct AllInclusive, item6_34),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_01,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-34"
		},
	{ ATF_POINTER, 204, offsetof(struct AllInclusive, item6_35),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_02,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-35"
		},
	{ ATF_POINTER, 203, offsetof(struct AllInclusive, item6_36),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_03,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-36"
		},
	{ ATF_POINTER, 202, offsetof(struct AllInclusive, item6_37),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_04,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-37"
		},
	{ ATF_POINTER, 201, offsetof(struct AllInclusive, item6_38),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_05,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-38"
		},
	{ ATF_POINTER, 200, offsetof(struct AllInclusive, item6_39),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_06,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-39"
		},
	{ ATF_POINTER, 199, offsetof(struct AllInclusive, item6_40),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_07,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-40"
		},
	{ ATF_POINTER, 198, offsetof(struct AllInclusive, item6_41),
		(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_08,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-41"
		},
	{ ATF_POINTER, 197, offsetof(struct AllInclusive, item6_42),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_09,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-42"
		},
	{ ATF_POINTER, 196, offsetof(struct AllInclusive, item6_43),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathHistoryPointType_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-43"
		},
	{ ATF_POINTER, 195, offsetof(struct AllInclusive, item6_44),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PathPrediction,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-44"
		},
	{ ATF_POINTER, 194, offsetof(struct AllInclusive, item6_45),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-45"
		},
	{ ATF_POINTER, 193, offsetof(struct AllInclusive, item6_46),
		(ASN_TAG_CLASS_CONTEXT | (44 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionalAccuracy,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-46"
		},
	{ ATF_POINTER, 192, offsetof(struct AllInclusive, item6_47),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionConfidenceSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-47"
		},
	{ ATF_POINTER, 191, offsetof(struct AllInclusive, item6_48),
		(ASN_TAG_CLASS_CONTEXT | (46 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-48"
		},
	{ ATF_POINTER, 190, offsetof(struct AllInclusive, item6_49),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionOffsets,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-49"
		},
	{ ATF_POINTER, 189, offsetof(struct AllInclusive, item6_50),
		(ASN_TAG_CLASS_CONTEXT | (48 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RegionPointSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-50"
		},
	{ ATF_POINTER, 188, offsetof(struct AllInclusive, item6_51),
		(ASN_TAG_CLASS_CONTEXT | (49 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadSignID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-51"
		},
	{ ATF_POINTER, 187, offsetof(struct AllInclusive, item6_52),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCMHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-52"
		},
	{ ATF_POINTER, 186, offsetof(struct AllInclusive, item6_53),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCMmsg,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-53"
		},
	{ ATF_POINTER, 185, offsetof(struct AllInclusive, item6_54),
		(ASN_TAG_CLASS_CONTEXT | (52 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCMPackage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-54"
		},
	{ ATF_POINTER, 184, offsetof(struct AllInclusive, item6_55),
		(ASN_TAG_CLASS_CONTEXT | (53 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Sample,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-55"
		},
	{ ATF_POINTER, 183, offsetof(struct AllInclusive, item6_56),
		(ASN_TAG_CLASS_CONTEXT | (54 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ShapePointSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-56"
		},
	{ ATF_POINTER, 182, offsetof(struct AllInclusive, item6_57),
		(ASN_TAG_CLASS_CONTEXT | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalControlZone,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-57"
		},
	{ ATF_POINTER, 181, offsetof(struct AllInclusive, item6_58),
		(ASN_TAG_CLASS_CONTEXT | (56 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-58"
		},
	{ ATF_POINTER, 180, offsetof(struct AllInclusive, item6_59),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SnapshotDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-59"
		},
	{ ATF_POINTER, 179, offsetof(struct AllInclusive, item6_60),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Snapshot,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-60"
		},
	{ ATF_POINTER, 178, offsetof(struct AllInclusive, item6_61),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SnapshotTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-61"
		},
	{ ATF_POINTER, 177, offsetof(struct AllInclusive, item6_62),
		(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpecialLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-62"
		},
	{ ATF_POINTER, 176, offsetof(struct AllInclusive, item6_63),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedandHeadingandThrottleConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-63"
		},
	{ ATF_POINTER, 175, offsetof(struct AllInclusive, item6_64),
		(ASN_TAG_CLASS_CONTEXT | (62 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransmissionAndSpeed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-64"
		},
	{ ATF_POINTER, 174, offsetof(struct AllInclusive, item6_65),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ValidRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-65"
		},
	{ ATF_POINTER, 173, offsetof(struct AllInclusive, item6_66),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleComputedLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-66"
		},
	{ ATF_POINTER, 172, offsetof(struct AllInclusive, item6_67),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleIdent,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-67"
		},
	{ ATF_POINTER, 171, offsetof(struct AllInclusive, item6_68),
		(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleReferenceLane,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-68"
		},
	{ ATF_POINTER, 170, offsetof(struct AllInclusive, item6_69),
		(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSafetyExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-69"
		},
	{ ATF_POINTER, 169, offsetof(struct AllInclusive, item6_70),
		(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSize,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-70"
		},
	{ ATF_POINTER, 168, offsetof(struct AllInclusive, item6_71),
		(ASN_TAG_CLASS_CONTEXT | (69 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleStatusRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-71"
		},
	{ ATF_POINTER, 167, offsetof(struct AllInclusive, item6_72),
		(ASN_TAG_CLASS_CONTEXT | (70 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-72"
		},
	{ ATF_POINTER, 166, offsetof(struct AllInclusive, item6_73),
		(ASN_TAG_CLASS_CONTEXT | (71 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WiperStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-73"
		},
	{ ATF_POINTER, 165, offsetof(struct AllInclusive, item6_74),
		(ASN_TAG_CLASS_CONTEXT | (72 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataFrame,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-74"
		},
	{ ATF_POINTER, 164, offsetof(struct AllInclusive, item6_75),
		(ASN_TAG_CLASS_CONTEXT | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TireState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-75"
		},
	{ ATF_POINTER, 163, offsetof(struct AllInclusive, item6_76),
		(ASN_TAG_CLASS_CONTEXT | (74 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AxleState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-76"
		},
	{ ATF_POINTER, 162, offsetof(struct AllInclusive, item6_77),
		(ASN_TAG_CLASS_CONTEXT | (75 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ZoneState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-77"
		},
	{ ATF_POINTER, 161, offsetof(struct AllInclusive, item6_78),
		(ASN_TAG_CLASS_CONTEXT | (76 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITISCodesChoice,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item6-78"
		},
	{ ATF_POINTER, 160, offsetof(struct AllInclusive, item7_1),
		(ASN_TAG_CLASS_CONTEXT | (77 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Acceleration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-1"
		},
	{ ATF_POINTER, 159, offsetof(struct AllInclusive, item7_2),
		(ASN_TAG_CLASS_CONTEXT | (78 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccelerationConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-2"
		},
	{ ATF_POINTER, 158, offsetof(struct AllInclusive, item7_3),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AmbientAirPressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-3"
		},
	{ ATF_POINTER, 157, offsetof(struct AllInclusive, item7_4),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AmbientAirTemperature,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-4"
		},
	{ ATF_POINTER, 156, offsetof(struct AllInclusive, item7_5),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntiLockBrakeStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-5"
		},
	{ ATF_POINTER, 155, offsetof(struct AllInclusive, item7_6),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApproachNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-6"
		},
	{ ATF_POINTER, 154, offsetof(struct AllInclusive, item7_7),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuxiliaryBrakeStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-7"
		},
	{ ATF_POINTER, 153, offsetof(struct AllInclusive, item7_8),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BarrierAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-8"
		},
	{ ATF_POINTER, 152, offsetof(struct AllInclusive, item7_9),
		(ASN_TAG_CLASS_CONTEXT | (85 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BrakeAppliedPressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-9"
		},
	{ ATF_POINTER, 151, offsetof(struct AllInclusive, item7_10),
		(ASN_TAG_CLASS_CONTEXT | (86 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BrakeAppliedStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-10"
		},
	{ ATF_POINTER, 150, offsetof(struct AllInclusive, item7_11),
		(ASN_TAG_CLASS_CONTEXT | (87 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BrakeBoostApplied,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-11"
		},
	{ ATF_POINTER, 149, offsetof(struct AllInclusive, item7_12),
		(ASN_TAG_CLASS_CONTEXT | (88 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BumperHeightFront,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-12"
		},
	{ ATF_POINTER, 148, offsetof(struct AllInclusive, item7_13),
		(ASN_TAG_CLASS_CONTEXT | (89 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BumperHeightRear,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-13"
		},
	{ ATF_POINTER, 147, offsetof(struct AllInclusive, item7_14),
		(ASN_TAG_CLASS_CONTEXT | (90 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CodeWord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-14"
		},
	{ ATF_POINTER, 146, offsetof(struct AllInclusive, item7_15),
		(ASN_TAG_CLASS_CONTEXT | (91 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoefficientOfFriction,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-15"
		},
	{ ATF_POINTER, 145, offsetof(struct AllInclusive, item7_16),
		(ASN_TAG_CLASS_CONTEXT | (92 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ColorState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-16"
		},
	{ ATF_POINTER, 144, offsetof(struct AllInclusive, item7_17),
		(ASN_TAG_CLASS_CONTEXT | (93 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Count,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-17"
		},
	{ ATF_POINTER, 143, offsetof(struct AllInclusive, item7_18),
		(ASN_TAG_CLASS_CONTEXT | (94 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CrosswalkLaneAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-18"
		},
	{ ATF_POINTER, 142, offsetof(struct AllInclusive, item7_19),
		(ASN_TAG_CLASS_CONTEXT | (95 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-19"
		},
	{ ATF_POINTER, 141, offsetof(struct AllInclusive, item7_20),
		(ASN_TAG_CLASS_CONTEXT | (96 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-20"
		},
	{ ATF_POINTER, 140, offsetof(struct AllInclusive, item7_21),
		(ASN_TAG_CLASS_CONTEXT | (97 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DHour,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-21"
		},
	{ ATF_POINTER, 139, offsetof(struct AllInclusive, item7_22),
		(ASN_TAG_CLASS_CONTEXT | (98 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DirectionOfUse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-22"
		},
	{ ATF_POINTER, 138, offsetof(struct AllInclusive, item7_23),
		(ASN_TAG_CLASS_CONTEXT | (99 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DMinute,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-23"
		},
	{ ATF_POINTER, 137, offsetof(struct AllInclusive, item7_24),
		(ASN_TAG_CLASS_CONTEXT | (100 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DMonth,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-24"
		},
	{ ATF_POINTER, 136, offsetof(struct AllInclusive, item7_25),
		(ASN_TAG_CLASS_CONTEXT | (101 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DOffset,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-25"
		},
	{ ATF_POINTER, 135, offsetof(struct AllInclusive, item7_26),
		(ASN_TAG_CLASS_CONTEXT | (102 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivenLineOffset,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-26"
		},
	{ ATF_POINTER, 134, offsetof(struct AllInclusive, item7_27),
		(ASN_TAG_CLASS_CONTEXT | (103 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DrivingWheelAngle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-27"
		},
	{ ATF_POINTER, 133, offsetof(struct AllInclusive, item7_28),
		(ASN_TAG_CLASS_CONTEXT | (104 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSecond,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-28"
		},
	{ ATF_POINTER, 132, offsetof(struct AllInclusive, item7_29),
		(ASN_TAG_CLASS_CONTEXT | (105 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSignalSeconds,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-29"
		},
	{ ATF_POINTER, 131, offsetof(struct AllInclusive, item7_30),
		(ASN_TAG_CLASS_CONTEXT | (106 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-30"
		},
	{ ATF_POINTER, 130, offsetof(struct AllInclusive, item7_31),
		(ASN_TAG_CLASS_CONTEXT | (107 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DYear,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-31"
		},
	{ ATF_POINTER, 129, offsetof(struct AllInclusive, item7_32),
		(ASN_TAG_CLASS_CONTEXT | (108 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ElevationConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-32"
		},
	{ ATF_POINTER, 128, offsetof(struct AllInclusive, item7_33),
		(ASN_TAG_CLASS_CONTEXT | (109 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Elevation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-33"
		},
	{ ATF_POINTER, 127, offsetof(struct AllInclusive, item7_34),
		(ASN_TAG_CLASS_CONTEXT | (110 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EmergencyDetails,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-34"
		},
	{ ATF_POINTER, 126, offsetof(struct AllInclusive, item7_35),
		(ASN_TAG_CLASS_CONTEXT | (111 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-35"
		},
	{ ATF_POINTER, 125, offsetof(struct AllInclusive, item7_36),
		(ASN_TAG_CLASS_CONTEXT | (112 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Extent,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-36"
		},
	{ ATF_POINTER, 124, offsetof(struct AllInclusive, item7_37),
		(ASN_TAG_CLASS_CONTEXT | (113 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExteriorLights,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-37"
		},
	{ ATF_POINTER, 123, offsetof(struct AllInclusive, item7_38),
		(ASN_TAG_CLASS_CONTEXT | (114 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FurtherInfoID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-38"
		},
	{ ATF_POINTER, 122, offsetof(struct AllInclusive, item7_39),
		(ASN_TAG_CLASS_CONTEXT | (115 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPSstatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-39"
		},
	{ ATF_POINTER, 121, offsetof(struct AllInclusive, item7_40),
		(ASN_TAG_CLASS_CONTEXT | (116 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HeadingConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-40"
		},
	{ ATF_POINTER, 120, offsetof(struct AllInclusive, item7_41),
		(ASN_TAG_CLASS_CONTEXT | (117 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Heading,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-41"
		},
	{ ATF_POINTER, 119, offsetof(struct AllInclusive, item7_42),
		(ASN_TAG_CLASS_CONTEXT | (118 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HeadingSlice,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-42"
		},
	{ ATF_POINTER, 118, offsetof(struct AllInclusive, item7_43),
		(ASN_TAG_CLASS_CONTEXT | (119 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionStatusObject,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-43"
		},
	{ ATF_POINTER, 117, offsetof(struct AllInclusive, item7_44),
		(ASN_TAG_CLASS_CONTEXT | (120 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-44"
		},
	{ ATF_POINTER, 116, offsetof(struct AllInclusive, item7_45),
		(ASN_TAG_CLASS_CONTEXT | (121 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AxleLocation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-45"
		},
	{ ATF_POINTER, 115, offsetof(struct AllInclusive, item7_46),
		(ASN_TAG_CLASS_CONTEXT | (122 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AxleWeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-46"
		},
	{ ATF_POINTER, 114, offsetof(struct AllInclusive, item7_47),
		(ASN_TAG_CLASS_CONTEXT | (123 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CargoWeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-47"
		},
	{ ATF_POINTER, 113, offsetof(struct AllInclusive, item7_48),
		(ASN_TAG_CLASS_CONTEXT | (124 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DriveAxleLiftAirPressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-48"
		},
	{ ATF_POINTER, 112, offsetof(struct AllInclusive, item7_49),
		(ASN_TAG_CLASS_CONTEXT | (125 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DriveAxleLocation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-49"
		},
	{ ATF_POINTER, 111, offsetof(struct AllInclusive, item7_50),
		(ASN_TAG_CLASS_CONTEXT | (126 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DriveAxleLubePressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-50"
		},
	{ ATF_POINTER, 110, offsetof(struct AllInclusive, item7_51),
		(ASN_TAG_CLASS_CONTEXT | (127 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DriveAxleTemperature,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-51"
		},
	{ ATF_POINTER, 109, offsetof(struct AllInclusive, item7_52),
		(ASN_TAG_CLASS_CONTEXT | (128 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SteeringAxleLubePressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-52"
		},
	{ ATF_POINTER, 108, offsetof(struct AllInclusive, item7_53),
		(ASN_TAG_CLASS_CONTEXT | (129 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SteeringAxleTemperature,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-53"
		},
	{ ATF_POINTER, 107, offsetof(struct AllInclusive, item7_54),
		(ASN_TAG_CLASS_CONTEXT | (130 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TireLeakageRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-54"
		},
	{ ATF_POINTER, 106, offsetof(struct AllInclusive, item7_55),
		(ASN_TAG_CLASS_CONTEXT | (131 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TireLocation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-55"
		},
	{ ATF_POINTER, 105, offsetof(struct AllInclusive, item7_56),
		(ASN_TAG_CLASS_CONTEXT | (132 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TirePressureThresholdDetection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-56"
		},
	{ ATF_POINTER, 104, offsetof(struct AllInclusive, item7_57),
		(ASN_TAG_CLASS_CONTEXT | (133 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TirePressure,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-57"
		},
	{ ATF_POINTER, 103, offsetof(struct AllInclusive, item7_58),
		(ASN_TAG_CLASS_CONTEXT | (134 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TireTemp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-58"
		},
	{ ATF_POINTER, 102, offsetof(struct AllInclusive, item7_59),
		(ASN_TAG_CLASS_CONTEXT | (135 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrailerWeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-59"
		},
	{ ATF_POINTER, 101, offsetof(struct AllInclusive, item7_60),
		(ASN_TAG_CLASS_CONTEXT | (136 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WheelEndElectFault,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-60"
		},
	{ ATF_POINTER, 100, offsetof(struct AllInclusive, item7_61),
		(ASN_TAG_CLASS_CONTEXT | (137 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WheelSensorStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-61"
		},
	{ ATF_POINTER, 99, offsetof(struct AllInclusive, item7_62),
		(ASN_TAG_CLASS_CONTEXT | (138 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-62"
		},
	{ ATF_POINTER, 98, offsetof(struct AllInclusive, item7_63),
		(ASN_TAG_CLASS_CONTEXT | (139 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneManeuverCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-63"
		},
	{ ATF_POINTER, 97, offsetof(struct AllInclusive, item7_64),
		(ASN_TAG_CLASS_CONTEXT | (140 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-64"
		},
	{ ATF_POINTER, 96, offsetof(struct AllInclusive, item7_65),
		(ASN_TAG_CLASS_CONTEXT | (141 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-65"
		},
	{ ATF_POINTER, 95, offsetof(struct AllInclusive, item7_66),
		(ASN_TAG_CLASS_CONTEXT | (142 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneWidth,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-66"
		},
	{ ATF_POINTER, 94, offsetof(struct AllInclusive, item7_67),
		(ASN_TAG_CLASS_CONTEXT | (143 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Latitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-67"
		},
	{ ATF_POINTER, 93, offsetof(struct AllInclusive, item7_68),
		(ASN_TAG_CLASS_CONTEXT | (144 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LayerID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-68"
		},
	{ ATF_POINTER, 92, offsetof(struct AllInclusive, item7_69),
		(ASN_TAG_CLASS_CONTEXT | (145 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LayerType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-69"
		},
	{ ATF_POINTER, 91, offsetof(struct AllInclusive, item7_70),
		(ASN_TAG_CLASS_CONTEXT | (146 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LightbarInUse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-70"
		},
	{ ATF_POINTER, 90, offsetof(struct AllInclusive, item7_71),
		(ASN_TAG_CLASS_CONTEXT | (147 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Longitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-71"
		},
	{ ATF_POINTER, 89, offsetof(struct AllInclusive, item7_72),
		(ASN_TAG_CLASS_CONTEXT | (148 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Location_quality,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-72"
		},
	{ ATF_POINTER, 88, offsetof(struct AllInclusive, item7_73),
		(ASN_TAG_CLASS_CONTEXT | (149 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Location_tech,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-73"
		},
	{ ATF_POINTER, 87, offsetof(struct AllInclusive, item7_74),
		(ASN_TAG_CLASS_CONTEXT | (150 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MinuteOfTheYear,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-74"
		},
	{ ATF_POINTER, 86, offsetof(struct AllInclusive, item7_75),
		(ASN_TAG_CLASS_CONTEXT | (151 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MinutesDuration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-75"
		},
	{ ATF_POINTER, 85, offsetof(struct AllInclusive, item7_76),
		(ASN_TAG_CLASS_CONTEXT | (152 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-76"
		},
	{ ATF_POINTER, 84, offsetof(struct AllInclusive, item7_77),
		(ASN_TAG_CLASS_CONTEXT | (153 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCRC,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-77"
		},
	{ ATF_POINTER, 83, offsetof(struct AllInclusive, item7_78),
		(ASN_TAG_CLASS_CONTEXT | (154 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MultiVehicleResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-78"
		},
	{ ATF_POINTER, 82, offsetof(struct AllInclusive, item7_79),
		(ASN_TAG_CLASS_CONTEXT | (155 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MUTCDCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-79"
		},
	{ ATF_POINTER, 81, offsetof(struct AllInclusive, item7_80),
		(ASN_TAG_CLASS_CONTEXT | (156 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NMEA_MsgType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-80"
		},
	{ ATF_POINTER, 80, offsetof(struct AllInclusive, item7_81),
		(ASN_TAG_CLASS_CONTEXT | (157 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NMEA_Payload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-81"
		},
	{ ATF_POINTER, 79, offsetof(struct AllInclusive, item7_82),
		(ASN_TAG_CLASS_CONTEXT | (158 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NMEA_Revision,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-82"
		},
	{ ATF_POINTER, 78, offsetof(struct AllInclusive, item7_83),
		(ASN_TAG_CLASS_CONTEXT | (159 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NTCIPVehicleclass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-83"
		},
	{ ATF_POINTER, 77, offsetof(struct AllInclusive, item7_84),
		(ASN_TAG_CLASS_CONTEXT | (160 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-84"
		},
	{ ATF_POINTER, 76, offsetof(struct AllInclusive, item7_85),
		(ASN_TAG_CLASS_CONTEXT | (161 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObstacleDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-85"
		},
	{ ATF_POINTER, 75, offsetof(struct AllInclusive, item7_86),
		(ASN_TAG_CLASS_CONTEXT | (162 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObstacleDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-86"
		},
	{ ATF_POINTER, 74, offsetof(struct AllInclusive, item7_87),
		(ASN_TAG_CLASS_CONTEXT | (163 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PayloadData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-87"
		},
	{ ATF_POINTER, 73, offsetof(struct AllInclusive, item7_88),
		(ASN_TAG_CLASS_CONTEXT | (164 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Payload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-88"
		},
	{ ATF_POINTER, 72, offsetof(struct AllInclusive, item7_89),
		(ASN_TAG_CLASS_CONTEXT | (165 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PedestrianDetect,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-89"
		},
	{ ATF_POINTER, 71, offsetof(struct AllInclusive, item7_90),
		(ASN_TAG_CLASS_CONTEXT | (166 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PedestrianSignalState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-90"
		},
	{ ATF_POINTER, 70, offsetof(struct AllInclusive, item7_91),
		(ASN_TAG_CLASS_CONTEXT | (167 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-91"
		},
	{ ATF_POINTER, 69, offsetof(struct AllInclusive, item7_92),
		(ASN_TAG_CLASS_CONTEXT | (168 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PreemptState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-92"
		},
	{ ATF_POINTER, 68, offsetof(struct AllInclusive, item7_93),
		(ASN_TAG_CLASS_CONTEXT | (169 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Priority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-93"
		},
	{ ATF_POINTER, 67, offsetof(struct AllInclusive, item7_94),
		(ASN_TAG_CLASS_CONTEXT | (170 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PriorityState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-94"
		},
	{ ATF_POINTER, 66, offsetof(struct AllInclusive, item7_95),
		(ASN_TAG_CLASS_CONTEXT | (171 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProbeSegmentNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-95"
		},
	{ ATF_POINTER, 65, offsetof(struct AllInclusive, item7_96),
		(ASN_TAG_CLASS_CONTEXT | (172 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RainSensor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-96"
		},
	{ ATF_POINTER, 64, offsetof(struct AllInclusive, item7_97),
		(ASN_TAG_CLASS_CONTEXT | (173 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestedItem,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-97"
		},
	{ ATF_POINTER, 63, offsetof(struct AllInclusive, item7_98),
		(ASN_TAG_CLASS_CONTEXT | (174 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResponseType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-98"
		},
	{ ATF_POINTER, 62, offsetof(struct AllInclusive, item7_99),
		(ASN_TAG_CLASS_CONTEXT | (175 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCM_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-99"
		},
	{ ATF_POINTER, 61, offsetof(struct AllInclusive, item7_100),
		(ASN_TAG_CLASS_CONTEXT | (176 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCM_Payload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-100"
		},
	{ ATF_POINTER, 60, offsetof(struct AllInclusive, item7_101),
		(ASN_TAG_CLASS_CONTEXT | (177 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RTCM_Revision,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-101"
		},
	{ ATF_POINTER, 59, offsetof(struct AllInclusive, item7_102),
		(ASN_TAG_CLASS_CONTEXT | (178 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalLightState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-102"
		},
	{ ATF_POINTER, 58, offsetof(struct AllInclusive, item7_103),
		(ASN_TAG_CLASS_CONTEXT | (179 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalReqScheme,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-103"
		},
	{ ATF_POINTER, 57, offsetof(struct AllInclusive, item7_104),
		(ASN_TAG_CLASS_CONTEXT | (180 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-104"
		},
	{ ATF_POINTER, 56, offsetof(struct AllInclusive, item7_105),
		(ASN_TAG_CLASS_CONTEXT | (181 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignPrority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-105"
		},
	{ ATF_POINTER, 55, offsetof(struct AllInclusive, item7_106),
		(ASN_TAG_CLASS_CONTEXT | (182 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SirenInUse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-106"
		},
	{ ATF_POINTER, 54, offsetof(struct AllInclusive, item7_107),
		(ASN_TAG_CLASS_CONTEXT | (183 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpecialLaneAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-107"
		},
	{ ATF_POINTER, 53, offsetof(struct AllInclusive, item7_108),
		(ASN_TAG_CLASS_CONTEXT | (184 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpecialSignalState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-108"
		},
	{ ATF_POINTER, 52, offsetof(struct AllInclusive, item7_109),
		(ASN_TAG_CLASS_CONTEXT | (185 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-109"
		},
	{ ATF_POINTER, 51, offsetof(struct AllInclusive, item7_110),
		(ASN_TAG_CLASS_CONTEXT | (186 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-110"
		},
	{ ATF_POINTER, 50, offsetof(struct AllInclusive, item7_111),
		(ASN_TAG_CLASS_CONTEXT | (187 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StabilityControlStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-111"
		},
	{ ATF_POINTER, 49, offsetof(struct AllInclusive, item7_112),
		(ASN_TAG_CLASS_CONTEXT | (188 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StateConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-112"
		},
	{ ATF_POINTER, 48, offsetof(struct AllInclusive, item7_113),
		(ASN_TAG_CLASS_CONTEXT | (189 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SteeringWheelAngleConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-113"
		},
	{ ATF_POINTER, 47, offsetof(struct AllInclusive, item7_114),
		(ASN_TAG_CLASS_CONTEXT | (190 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SteeringWheelAngleRateOfChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-114"
		},
	{ ATF_POINTER, 46, offsetof(struct AllInclusive, item7_115),
		(ASN_TAG_CLASS_CONTEXT | (191 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SteeringWheelAngle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-115"
		},
	{ ATF_POINTER, 45, offsetof(struct AllInclusive, item7_116),
		(ASN_TAG_CLASS_CONTEXT | (192 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SunSensor,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-116"
		},
	{ ATF_POINTER, 44, offsetof(struct AllInclusive, item7_117),
		(ASN_TAG_CLASS_CONTEXT | (193 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-117"
		},
	{ ATF_POINTER, 43, offsetof(struct AllInclusive, item7_118),
		(ASN_TAG_CLASS_CONTEXT | (194 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TermDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-118"
		},
	{ ATF_POINTER, 42, offsetof(struct AllInclusive, item7_119),
		(ASN_TAG_CLASS_CONTEXT | (195 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TermTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-119"
		},
	{ ATF_POINTER, 41, offsetof(struct AllInclusive, item7_120),
		(ASN_TAG_CLASS_CONTEXT | (196 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThrottleConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-120"
		},
	{ ATF_POINTER, 40, offsetof(struct AllInclusive, item7_121),
		(ASN_TAG_CLASS_CONTEXT | (197 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThrottlePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-121"
		},
	{ ATF_POINTER, 39, offsetof(struct AllInclusive, item7_122),
		(ASN_TAG_CLASS_CONTEXT | (198 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-122"
		},
	{ ATF_POINTER, 38, offsetof(struct AllInclusive, item7_123),
		(ASN_TAG_CLASS_CONTEXT | (199 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-123"
		},
	{ ATF_POINTER, 37, offsetof(struct AllInclusive, item7_124),
		(ASN_TAG_CLASS_CONTEXT | (200 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TractionControlState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-124"
		},
	{ ATF_POINTER, 36, offsetof(struct AllInclusive, item7_125),
		(ASN_TAG_CLASS_CONTEXT | (201 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransitPreEmptionRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-125"
		},
	{ ATF_POINTER, 35, offsetof(struct AllInclusive, item7_126),
		(ASN_TAG_CLASS_CONTEXT | (202 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransitStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-126"
		},
	{ ATF_POINTER, 34, offsetof(struct AllInclusive, item7_127),
		(ASN_TAG_CLASS_CONTEXT | (203 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransmissionState,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-127"
		},
	{ ATF_POINTER, 33, offsetof(struct AllInclusive, item7_128),
		(ASN_TAG_CLASS_CONTEXT | (204 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TxTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-128"
		},
	{ ATF_POINTER, 32, offsetof(struct AllInclusive, item7_129),
		(ASN_TAG_CLASS_CONTEXT | (205 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TravelerInfoType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-129"
		},
	{ ATF_POINTER, 31, offsetof(struct AllInclusive, item7_130),
		(ASN_TAG_CLASS_CONTEXT | (206 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniqueMSGID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-130"
		},
	{ ATF_POINTER, 30, offsetof(struct AllInclusive, item7_131),
		(ASN_TAG_CLASS_CONTEXT | (207 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URL_Base,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-131"
		},
	{ ATF_POINTER, 29, offsetof(struct AllInclusive, item7_132),
		(ASN_TAG_CLASS_CONTEXT | (208 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URL_Link,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-132"
		},
	{ ATF_POINTER, 28, offsetof(struct AllInclusive, item7_133),
		(ASN_TAG_CLASS_CONTEXT | (209 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URL_Short,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-133"
		},
	{ ATF_POINTER, 27, offsetof(struct AllInclusive, item7_134),
		(ASN_TAG_CLASS_CONTEXT | (210 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleHeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-134"
		},
	{ ATF_POINTER, 26, offsetof(struct AllInclusive, item7_135),
		(ASN_TAG_CLASS_CONTEXT | (211 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleLaneAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-135"
		},
	{ ATF_POINTER, 25, offsetof(struct AllInclusive, item7_136),
		(ASN_TAG_CLASS_CONTEXT | (212 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-136"
		},
	{ ATF_POINTER, 24, offsetof(struct AllInclusive, item7_137),
		(ASN_TAG_CLASS_CONTEXT | (213 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleMass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-137"
		},
	{ ATF_POINTER, 23, offsetof(struct AllInclusive, item7_138),
		(ASN_TAG_CLASS_CONTEXT | (214 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleRequestStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-138"
		},
	{ ATF_POINTER, 22, offsetof(struct AllInclusive, item7_139),
		(ASN_TAG_CLASS_CONTEXT | (215 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleStatusDeviceTypeTag,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-139"
		},
	{ ATF_POINTER, 21, offsetof(struct AllInclusive, item7_140),
		(ASN_TAG_CLASS_CONTEXT | (216 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-140"
		},
	{ ATF_POINTER, 20, offsetof(struct AllInclusive, item7_141),
		(ASN_TAG_CLASS_CONTEXT | (217 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleWidth,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-141"
		},
	{ ATF_POINTER, 19, offsetof(struct AllInclusive, item7_142),
		(ASN_TAG_CLASS_CONTEXT | (218 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VerticalAccelerationThreshold,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-142"
		},
	{ ATF_POINTER, 18, offsetof(struct AllInclusive, item7_143),
		(ASN_TAG_CLASS_CONTEXT | (219 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VerticalAcceleration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-143"
		},
	{ ATF_POINTER, 17, offsetof(struct AllInclusive, item7_144),
		(ASN_TAG_CLASS_CONTEXT | (220 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VINstring,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-144"
		},
	{ ATF_POINTER, 16, offsetof(struct AllInclusive, item7_145),
		(ASN_TAG_CLASS_CONTEXT | (221 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WiperRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-145"
		},
	{ ATF_POINTER, 15, offsetof(struct AllInclusive, item7_146),
		(ASN_TAG_CLASS_CONTEXT | (222 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WiperStatusFront,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-146"
		},
	{ ATF_POINTER, 14, offsetof(struct AllInclusive, item7_147),
		(ASN_TAG_CLASS_CONTEXT | (223 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WiperStatusRear,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-147"
		},
	{ ATF_POINTER, 13, offsetof(struct AllInclusive, item7_148),
		(ASN_TAG_CLASS_CONTEXT | (224 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_YawRateConfidence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-148"
		},
	{ ATF_POINTER, 12, offsetof(struct AllInclusive, item7_149),
		(ASN_TAG_CLASS_CONTEXT | (225 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_YawRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item7-149"
		},
	{ ATF_POINTER, 11, offsetof(struct AllInclusive, item8_1),
		(ASN_TAG_CLASS_CONTEXT | (226 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncidentResponseEquipment,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-1"
		},
	{ ATF_POINTER, 10, offsetof(struct AllInclusive, item8_2),
		(ASN_TAG_CLASS_CONTEXT | (227 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIStext,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-2"
		},
	{ ATF_POINTER, 9, offsetof(struct AllInclusive, item8_3),
		(ASN_TAG_CLASS_CONTEXT | (228 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResponderGroupAffected,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-3"
		},
	{ ATF_POINTER, 8, offsetof(struct AllInclusive, item8_4),
		(ASN_TAG_CLASS_CONTEXT | (229 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleGroupAffected,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-4"
		},
	{ ATF_POINTER, 7, offsetof(struct AllInclusive, item8_5),
		(ASN_TAG_CLASS_CONTEXT | (230 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodesAndText,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-5"
		},
	{ ATF_POINTER, 6, offsetof(struct AllInclusive, item8_6),
		(ASN_TAG_CLASS_CONTEXT | (231 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EssMobileFriction,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-6"
		},
	{ ATF_POINTER, 5, offsetof(struct AllInclusive, item8_7),
		(ASN_TAG_CLASS_CONTEXT | (232 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EssPrecipRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-7"
		},
	{ ATF_POINTER, 4, offsetof(struct AllInclusive, item8_8),
		(ASN_TAG_CLASS_CONTEXT | (233 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EssPrecipSituation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-8"
		},
	{ ATF_POINTER, 3, offsetof(struct AllInclusive, item8_9),
		(ASN_TAG_CLASS_CONTEXT | (234 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EssPrecipYesNo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-9"
		},
	{ ATF_POINTER, 2, offsetof(struct AllInclusive, item8_10),
		(ASN_TAG_CLASS_CONTEXT | (235 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EssSolarRadiation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-10"
		},
	{ ATF_POINTER, 1, offsetof(struct AllInclusive, item8_11),
		(ASN_TAG_CLASS_CONTEXT | (236 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ITIScodes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"item8-11"
		},
};
static ber_tlv_tag_t asn_DEF_AllInclusive_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AllInclusive_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* item6-1 at 477 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* item6-2 at 478 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* item6-4 at 480 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* item6-5 at 481 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* item6-6 at 482 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* item6-7 at 483 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* item6-8 at 484 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* item6-9 at 485 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* item6-10 at 486 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* item6-11 at 487 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* item6-12 at 488 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* item6-13 at 489 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* item6-14 at 490 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* item6-15 at 491 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* item6-16 at 492 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* item6-17 at 493 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* item6-18 at 494 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* item6-19 at 495 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* item6-20 at 496 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* item6-21 at 497 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* item6-22 at 498 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* item6-23 at 499 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* item6-24 at 500 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* item6-25 at 501 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* item6-26 at 502 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* item6-27 at 503 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* item6-28 at 504 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* item6-29 at 505 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* item6-30 at 506 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* item6-31 at 507 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* item6-32 at 508 */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* item6-33 at 509 */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* item6-34 at 510 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* item6-35 at 511 */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* item6-36 at 512 */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* item6-37 at 513 */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 }, /* item6-38 at 514 */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 37, 0, 0 }, /* item6-39 at 515 */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 38, 0, 0 }, /* item6-40 at 516 */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 39, 0, 0 }, /* item6-41 at 517 */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 40, 0, 0 }, /* item6-42 at 518 */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 41, 0, 0 }, /* item6-43 at 519 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 42, 0, 0 }, /* item6-44 at 520 */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 43, 0, 0 }, /* item6-45 at 521 */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 44, 0, 0 }, /* item6-46 at 522 */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 45, 0, 0 }, /* item6-47 at 523 */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 46, 0, 0 }, /* item6-48 at 524 */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 47, 0, 0 }, /* item6-49 at 525 */
    { (ASN_TAG_CLASS_CONTEXT | (48 << 2)), 48, 0, 0 }, /* item6-50 at 526 */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 49, 0, 0 }, /* item6-51 at 527 */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 50, 0, 0 }, /* item6-52 at 528 */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 51, 0, 0 }, /* item6-53 at 529 */
    { (ASN_TAG_CLASS_CONTEXT | (52 << 2)), 52, 0, 0 }, /* item6-54 at 530 */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 53, 0, 0 }, /* item6-55 at 531 */
    { (ASN_TAG_CLASS_CONTEXT | (54 << 2)), 54, 0, 0 }, /* item6-56 at 532 */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 55, 0, 0 }, /* item6-57 at 533 */
    { (ASN_TAG_CLASS_CONTEXT | (56 << 2)), 56, 0, 0 }, /* item6-58 at 534 */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 57, 0, 0 }, /* item6-59 at 535 */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 58, 0, 0 }, /* item6-60 at 536 */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 59, 0, 0 }, /* item6-61 at 537 */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 60, 0, 0 }, /* item6-62 at 538 */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 61, 0, 0 }, /* item6-63 at 539 */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 62, 0, 0 }, /* item6-64 at 540 */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 63, 0, 0 }, /* item6-65 at 541 */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 64, 0, 0 }, /* item6-66 at 542 */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 65, 0, 0 }, /* item6-67 at 543 */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 66, 0, 0 }, /* item6-68 at 544 */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 67, 0, 0 }, /* item6-69 at 545 */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 68, 0, 0 }, /* item6-70 at 546 */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 69, 0, 0 }, /* item6-71 at 547 */
    { (ASN_TAG_CLASS_CONTEXT | (70 << 2)), 70, 0, 0 }, /* item6-72 at 548 */
    { (ASN_TAG_CLASS_CONTEXT | (71 << 2)), 71, 0, 0 }, /* item6-73 at 549 */
    { (ASN_TAG_CLASS_CONTEXT | (72 << 2)), 72, 0, 0 }, /* item6-74 at 550 */
    { (ASN_TAG_CLASS_CONTEXT | (73 << 2)), 73, 0, 0 }, /* item6-75 at 551 */
    { (ASN_TAG_CLASS_CONTEXT | (74 << 2)), 74, 0, 0 }, /* item6-76 at 552 */
    { (ASN_TAG_CLASS_CONTEXT | (75 << 2)), 75, 0, 0 }, /* item6-77 at 553 */
    { (ASN_TAG_CLASS_CONTEXT | (76 << 2)), 76, 0, 0 }, /* item6-78 at 554 */
    { (ASN_TAG_CLASS_CONTEXT | (77 << 2)), 77, 0, 0 }, /* item7-1 at 558 */
    { (ASN_TAG_CLASS_CONTEXT | (78 << 2)), 78, 0, 0 }, /* item7-2 at 559 */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 79, 0, 0 }, /* item7-3 at 560 */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 80, 0, 0 }, /* item7-4 at 561 */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 81, 0, 0 }, /* item7-5 at 562 */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 82, 0, 0 }, /* item7-6 at 563 */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 83, 0, 0 }, /* item7-7 at 564 */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 84, 0, 0 }, /* item7-8 at 565 */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 85, 0, 0 }, /* item7-9 at 566 */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 86, 0, 0 }, /* item7-10 at 567 */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 87, 0, 0 }, /* item7-11 at 568 */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 88, 0, 0 }, /* item7-12 at 569 */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 89, 0, 0 }, /* item7-13 at 570 */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 90, 0, 0 }, /* item7-14 at 571 */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 91, 0, 0 }, /* item7-15 at 572 */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 92, 0, 0 }, /* item7-16 at 573 */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 93, 0, 0 }, /* item7-17 at 574 */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 94, 0, 0 }, /* item7-18 at 575 */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 95, 0, 0 }, /* item7-19 at 576 */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 96, 0, 0 }, /* item7-20 at 577 */
    { (ASN_TAG_CLASS_CONTEXT | (97 << 2)), 97, 0, 0 }, /* item7-21 at 578 */
    { (ASN_TAG_CLASS_CONTEXT | (98 << 2)), 98, 0, 0 }, /* item7-22 at 579 */
    { (ASN_TAG_CLASS_CONTEXT | (99 << 2)), 99, 0, 0 }, /* item7-23 at 580 */
    { (ASN_TAG_CLASS_CONTEXT | (100 << 2)), 100, 0, 0 }, /* item7-24 at 581 */
    { (ASN_TAG_CLASS_CONTEXT | (101 << 2)), 101, 0, 0 }, /* item7-25 at 582 */
    { (ASN_TAG_CLASS_CONTEXT | (102 << 2)), 102, 0, 0 }, /* item7-26 at 583 */
    { (ASN_TAG_CLASS_CONTEXT | (103 << 2)), 103, 0, 0 }, /* item7-27 at 584 */
    { (ASN_TAG_CLASS_CONTEXT | (104 << 2)), 104, 0, 0 }, /* item7-28 at 585 */
    { (ASN_TAG_CLASS_CONTEXT | (105 << 2)), 105, 0, 0 }, /* item7-29 at 586 */
    { (ASN_TAG_CLASS_CONTEXT | (106 << 2)), 106, 0, 0 }, /* item7-30 at 587 */
    { (ASN_TAG_CLASS_CONTEXT | (107 << 2)), 107, 0, 0 }, /* item7-31 at 588 */
    { (ASN_TAG_CLASS_CONTEXT | (108 << 2)), 108, 0, 0 }, /* item7-32 at 589 */
    { (ASN_TAG_CLASS_CONTEXT | (109 << 2)), 109, 0, 0 }, /* item7-33 at 590 */
    { (ASN_TAG_CLASS_CONTEXT | (110 << 2)), 110, 0, 0 }, /* item7-34 at 591 */
    { (ASN_TAG_CLASS_CONTEXT | (111 << 2)), 111, 0, 0 }, /* item7-35 at 592 */
    { (ASN_TAG_CLASS_CONTEXT | (112 << 2)), 112, 0, 0 }, /* item7-36 at 593 */
    { (ASN_TAG_CLASS_CONTEXT | (113 << 2)), 113, 0, 0 }, /* item7-37 at 594 */
    { (ASN_TAG_CLASS_CONTEXT | (114 << 2)), 114, 0, 0 }, /* item7-38 at 595 */
    { (ASN_TAG_CLASS_CONTEXT | (115 << 2)), 115, 0, 0 }, /* item7-39 at 596 */
    { (ASN_TAG_CLASS_CONTEXT | (116 << 2)), 116, 0, 0 }, /* item7-40 at 597 */
    { (ASN_TAG_CLASS_CONTEXT | (117 << 2)), 117, 0, 0 }, /* item7-41 at 598 */
    { (ASN_TAG_CLASS_CONTEXT | (118 << 2)), 118, 0, 0 }, /* item7-42 at 599 */
    { (ASN_TAG_CLASS_CONTEXT | (119 << 2)), 119, 0, 0 }, /* item7-43 at 600 */
    { (ASN_TAG_CLASS_CONTEXT | (120 << 2)), 120, 0, 0 }, /* item7-44 at 601 */
    { (ASN_TAG_CLASS_CONTEXT | (121 << 2)), 121, 0, 0 }, /* item7-45 at 602 */
    { (ASN_TAG_CLASS_CONTEXT | (122 << 2)), 122, 0, 0 }, /* item7-46 at 603 */
    { (ASN_TAG_CLASS_CONTEXT | (123 << 2)), 123, 0, 0 }, /* item7-47 at 604 */
    { (ASN_TAG_CLASS_CONTEXT | (124 << 2)), 124, 0, 0 }, /* item7-48 at 605 */
    { (ASN_TAG_CLASS_CONTEXT | (125 << 2)), 125, 0, 0 }, /* item7-49 at 606 */
    { (ASN_TAG_CLASS_CONTEXT | (126 << 2)), 126, 0, 0 }, /* item7-50 at 607 */
    { (ASN_TAG_CLASS_CONTEXT | (127 << 2)), 127, 0, 0 }, /* item7-51 at 608 */
    { (ASN_TAG_CLASS_CONTEXT | (128 << 2)), 128, 0, 0 }, /* item7-52 at 609 */
    { (ASN_TAG_CLASS_CONTEXT | (129 << 2)), 129, 0, 0 }, /* item7-53 at 610 */
    { (ASN_TAG_CLASS_CONTEXT | (130 << 2)), 130, 0, 0 }, /* item7-54 at 611 */
    { (ASN_TAG_CLASS_CONTEXT | (131 << 2)), 131, 0, 0 }, /* item7-55 at 612 */
    { (ASN_TAG_CLASS_CONTEXT | (132 << 2)), 132, 0, 0 }, /* item7-56 at 613 */
    { (ASN_TAG_CLASS_CONTEXT | (133 << 2)), 133, 0, 0 }, /* item7-57 at 614 */
    { (ASN_TAG_CLASS_CONTEXT | (134 << 2)), 134, 0, 0 }, /* item7-58 at 615 */
    { (ASN_TAG_CLASS_CONTEXT | (135 << 2)), 135, 0, 0 }, /* item7-59 at 616 */
    { (ASN_TAG_CLASS_CONTEXT | (136 << 2)), 136, 0, 0 }, /* item7-60 at 617 */
    { (ASN_TAG_CLASS_CONTEXT | (137 << 2)), 137, 0, 0 }, /* item7-61 at 618 */
    { (ASN_TAG_CLASS_CONTEXT | (138 << 2)), 138, 0, 0 }, /* item7-62 at 619 */
    { (ASN_TAG_CLASS_CONTEXT | (139 << 2)), 139, 0, 0 }, /* item7-63 at 620 */
    { (ASN_TAG_CLASS_CONTEXT | (140 << 2)), 140, 0, 0 }, /* item7-64 at 621 */
    { (ASN_TAG_CLASS_CONTEXT | (141 << 2)), 141, 0, 0 }, /* item7-65 at 622 */
    { (ASN_TAG_CLASS_CONTEXT | (142 << 2)), 142, 0, 0 }, /* item7-66 at 623 */
    { (ASN_TAG_CLASS_CONTEXT | (143 << 2)), 143, 0, 0 }, /* item7-67 at 624 */
    { (ASN_TAG_CLASS_CONTEXT | (144 << 2)), 144, 0, 0 }, /* item7-68 at 625 */
    { (ASN_TAG_CLASS_CONTEXT | (145 << 2)), 145, 0, 0 }, /* item7-69 at 626 */
    { (ASN_TAG_CLASS_CONTEXT | (146 << 2)), 146, 0, 0 }, /* item7-70 at 627 */
    { (ASN_TAG_CLASS_CONTEXT | (147 << 2)), 147, 0, 0 }, /* item7-71 at 628 */
    { (ASN_TAG_CLASS_CONTEXT | (148 << 2)), 148, 0, 0 }, /* item7-72 at 629 */
    { (ASN_TAG_CLASS_CONTEXT | (149 << 2)), 149, 0, 0 }, /* item7-73 at 630 */
    { (ASN_TAG_CLASS_CONTEXT | (150 << 2)), 150, 0, 0 }, /* item7-74 at 631 */
    { (ASN_TAG_CLASS_CONTEXT | (151 << 2)), 151, 0, 0 }, /* item7-75 at 632 */
    { (ASN_TAG_CLASS_CONTEXT | (152 << 2)), 152, 0, 0 }, /* item7-76 at 633 */
    { (ASN_TAG_CLASS_CONTEXT | (153 << 2)), 153, 0, 0 }, /* item7-77 at 634 */
    { (ASN_TAG_CLASS_CONTEXT | (154 << 2)), 154, 0, 0 }, /* item7-78 at 635 */
    { (ASN_TAG_CLASS_CONTEXT | (155 << 2)), 155, 0, 0 }, /* item7-79 at 636 */
    { (ASN_TAG_CLASS_CONTEXT | (156 << 2)), 156, 0, 0 }, /* item7-80 at 637 */
    { (ASN_TAG_CLASS_CONTEXT | (157 << 2)), 157, 0, 0 }, /* item7-81 at 638 */
    { (ASN_TAG_CLASS_CONTEXT | (158 << 2)), 158, 0, 0 }, /* item7-82 at 639 */
    { (ASN_TAG_CLASS_CONTEXT | (159 << 2)), 159, 0, 0 }, /* item7-83 at 640 */
    { (ASN_TAG_CLASS_CONTEXT | (160 << 2)), 160, 0, 0 }, /* item7-84 at 641 */
    { (ASN_TAG_CLASS_CONTEXT | (161 << 2)), 161, 0, 0 }, /* item7-85 at 642 */
    { (ASN_TAG_CLASS_CONTEXT | (162 << 2)), 162, 0, 0 }, /* item7-86 at 643 */
    { (ASN_TAG_CLASS_CONTEXT | (163 << 2)), 163, 0, 0 }, /* item7-87 at 644 */
    { (ASN_TAG_CLASS_CONTEXT | (164 << 2)), 164, 0, 0 }, /* item7-88 at 645 */
    { (ASN_TAG_CLASS_CONTEXT | (165 << 2)), 165, 0, 0 }, /* item7-89 at 646 */
    { (ASN_TAG_CLASS_CONTEXT | (166 << 2)), 166, 0, 0 }, /* item7-90 at 647 */
    { (ASN_TAG_CLASS_CONTEXT | (167 << 2)), 167, 0, 0 }, /* item7-91 at 648 */
    { (ASN_TAG_CLASS_CONTEXT | (168 << 2)), 168, 0, 0 }, /* item7-92 at 649 */
    { (ASN_TAG_CLASS_CONTEXT | (169 << 2)), 169, 0, 0 }, /* item7-93 at 650 */
    { (ASN_TAG_CLASS_CONTEXT | (170 << 2)), 170, 0, 0 }, /* item7-94 at 651 */
    { (ASN_TAG_CLASS_CONTEXT | (171 << 2)), 171, 0, 0 }, /* item7-95 at 652 */
    { (ASN_TAG_CLASS_CONTEXT | (172 << 2)), 172, 0, 0 }, /* item7-96 at 653 */
    { (ASN_TAG_CLASS_CONTEXT | (173 << 2)), 173, 0, 0 }, /* item7-97 at 654 */
    { (ASN_TAG_CLASS_CONTEXT | (174 << 2)), 174, 0, 0 }, /* item7-98 at 655 */
    { (ASN_TAG_CLASS_CONTEXT | (175 << 2)), 175, 0, 0 }, /* item7-99 at 656 */
    { (ASN_TAG_CLASS_CONTEXT | (176 << 2)), 176, 0, 0 }, /* item7-100 at 657 */
    { (ASN_TAG_CLASS_CONTEXT | (177 << 2)), 177, 0, 0 }, /* item7-101 at 658 */
    { (ASN_TAG_CLASS_CONTEXT | (178 << 2)), 178, 0, 0 }, /* item7-102 at 659 */
    { (ASN_TAG_CLASS_CONTEXT | (179 << 2)), 179, 0, 0 }, /* item7-103 at 660 */
    { (ASN_TAG_CLASS_CONTEXT | (180 << 2)), 180, 0, 0 }, /* item7-104 at 661 */
    { (ASN_TAG_CLASS_CONTEXT | (181 << 2)), 181, 0, 0 }, /* item7-105 at 662 */
    { (ASN_TAG_CLASS_CONTEXT | (182 << 2)), 182, 0, 0 }, /* item7-106 at 663 */
    { (ASN_TAG_CLASS_CONTEXT | (183 << 2)), 183, 0, 0 }, /* item7-107 at 664 */
    { (ASN_TAG_CLASS_CONTEXT | (184 << 2)), 184, 0, 0 }, /* item7-108 at 665 */
    { (ASN_TAG_CLASS_CONTEXT | (185 << 2)), 185, 0, 0 }, /* item7-109 at 666 */
    { (ASN_TAG_CLASS_CONTEXT | (186 << 2)), 186, 0, 0 }, /* item7-110 at 667 */
    { (ASN_TAG_CLASS_CONTEXT | (187 << 2)), 187, 0, 0 }, /* item7-111 at 668 */
    { (ASN_TAG_CLASS_CONTEXT | (188 << 2)), 188, 0, 0 }, /* item7-112 at 669 */
    { (ASN_TAG_CLASS_CONTEXT | (189 << 2)), 189, 0, 0 }, /* item7-113 at 670 */
    { (ASN_TAG_CLASS_CONTEXT | (190 << 2)), 190, 0, 0 }, /* item7-114 at 671 */
    { (ASN_TAG_CLASS_CONTEXT | (191 << 2)), 191, 0, 0 }, /* item7-115 at 672 */
    { (ASN_TAG_CLASS_CONTEXT | (192 << 2)), 192, 0, 0 }, /* item7-116 at 673 */
    { (ASN_TAG_CLASS_CONTEXT | (193 << 2)), 193, 0, 0 }, /* item7-117 at 674 */
    { (ASN_TAG_CLASS_CONTEXT | (194 << 2)), 194, 0, 0 }, /* item7-118 at 675 */
    { (ASN_TAG_CLASS_CONTEXT | (195 << 2)), 195, 0, 0 }, /* item7-119 at 676 */
    { (ASN_TAG_CLASS_CONTEXT | (196 << 2)), 196, 0, 0 }, /* item7-120 at 677 */
    { (ASN_TAG_CLASS_CONTEXT | (197 << 2)), 197, 0, 0 }, /* item7-121 at 678 */
    { (ASN_TAG_CLASS_CONTEXT | (198 << 2)), 198, 0, 0 }, /* item7-122 at 679 */
    { (ASN_TAG_CLASS_CONTEXT | (199 << 2)), 199, 0, 0 }, /* item7-123 at 680 */
    { (ASN_TAG_CLASS_CONTEXT | (200 << 2)), 200, 0, 0 }, /* item7-124 at 681 */
    { (ASN_TAG_CLASS_CONTEXT | (201 << 2)), 201, 0, 0 }, /* item7-125 at 682 */
    { (ASN_TAG_CLASS_CONTEXT | (202 << 2)), 202, 0, 0 }, /* item7-126 at 683 */
    { (ASN_TAG_CLASS_CONTEXT | (203 << 2)), 203, 0, 0 }, /* item7-127 at 684 */
    { (ASN_TAG_CLASS_CONTEXT | (204 << 2)), 204, 0, 0 }, /* item7-128 at 685 */
    { (ASN_TAG_CLASS_CONTEXT | (205 << 2)), 205, 0, 0 }, /* item7-129 at 686 */
    { (ASN_TAG_CLASS_CONTEXT | (206 << 2)), 206, 0, 0 }, /* item7-130 at 687 */
    { (ASN_TAG_CLASS_CONTEXT | (207 << 2)), 207, 0, 0 }, /* item7-131 at 688 */
    { (ASN_TAG_CLASS_CONTEXT | (208 << 2)), 208, 0, 0 }, /* item7-132 at 689 */
    { (ASN_TAG_CLASS_CONTEXT | (209 << 2)), 209, 0, 0 }, /* item7-133 at 690 */
    { (ASN_TAG_CLASS_CONTEXT | (210 << 2)), 210, 0, 0 }, /* item7-134 at 691 */
    { (ASN_TAG_CLASS_CONTEXT | (211 << 2)), 211, 0, 0 }, /* item7-135 at 692 */
    { (ASN_TAG_CLASS_CONTEXT | (212 << 2)), 212, 0, 0 }, /* item7-136 at 693 */
    { (ASN_TAG_CLASS_CONTEXT | (213 << 2)), 213, 0, 0 }, /* item7-137 at 694 */
    { (ASN_TAG_CLASS_CONTEXT | (214 << 2)), 214, 0, 0 }, /* item7-138 at 695 */
    { (ASN_TAG_CLASS_CONTEXT | (215 << 2)), 215, 0, 0 }, /* item7-139 at 696 */
    { (ASN_TAG_CLASS_CONTEXT | (216 << 2)), 216, 0, 0 }, /* item7-140 at 697 */
    { (ASN_TAG_CLASS_CONTEXT | (217 << 2)), 217, 0, 0 }, /* item7-141 at 698 */
    { (ASN_TAG_CLASS_CONTEXT | (218 << 2)), 218, 0, 0 }, /* item7-142 at 699 */
    { (ASN_TAG_CLASS_CONTEXT | (219 << 2)), 219, 0, 0 }, /* item7-143 at 700 */
    { (ASN_TAG_CLASS_CONTEXT | (220 << 2)), 220, 0, 0 }, /* item7-144 at 701 */
    { (ASN_TAG_CLASS_CONTEXT | (221 << 2)), 221, 0, 0 }, /* item7-145 at 702 */
    { (ASN_TAG_CLASS_CONTEXT | (222 << 2)), 222, 0, 0 }, /* item7-146 at 703 */
    { (ASN_TAG_CLASS_CONTEXT | (223 << 2)), 223, 0, 0 }, /* item7-147 at 704 */
    { (ASN_TAG_CLASS_CONTEXT | (224 << 2)), 224, 0, 0 }, /* item7-148 at 705 */
    { (ASN_TAG_CLASS_CONTEXT | (225 << 2)), 225, 0, 0 }, /* item7-149 at 706 */
    { (ASN_TAG_CLASS_CONTEXT | (226 << 2)), 226, 0, 0 }, /* item8-1 at 709 */
    { (ASN_TAG_CLASS_CONTEXT | (227 << 2)), 227, 0, 0 }, /* item8-2 at 710 */
    { (ASN_TAG_CLASS_CONTEXT | (228 << 2)), 228, 0, 0 }, /* item8-3 at 711 */
    { (ASN_TAG_CLASS_CONTEXT | (229 << 2)), 229, 0, 0 }, /* item8-4 at 712 */
    { (ASN_TAG_CLASS_CONTEXT | (230 << 2)), 230, 0, 0 }, /* item8-5 at 713 */
    { (ASN_TAG_CLASS_CONTEXT | (231 << 2)), 231, 0, 0 }, /* item8-6 at 714 */
    { (ASN_TAG_CLASS_CONTEXT | (232 << 2)), 232, 0, 0 }, /* item8-7 at 715 */
    { (ASN_TAG_CLASS_CONTEXT | (233 << 2)), 233, 0, 0 }, /* item8-8 at 716 */
    { (ASN_TAG_CLASS_CONTEXT | (234 << 2)), 234, 0, 0 }, /* item8-9 at 717 */
    { (ASN_TAG_CLASS_CONTEXT | (235 << 2)), 235, 0, 0 }, /* item8-10 at 718 */
    { (ASN_TAG_CLASS_CONTEXT | (236 << 2)), 236, 0, 0 } /* item8-11 at 719 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AllInclusive_specs_1 = {
	sizeof(struct AllInclusive),
	offsetof(struct AllInclusive, _asn_ctx),
	asn_MAP_AllInclusive_tag2el_1,
	237,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	236,	/* Start extensions */
	238	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AllInclusive = {
	"AllInclusive",
	"AllInclusive",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AllInclusive_tags_1,
	sizeof(asn_DEF_AllInclusive_tags_1)
		/sizeof(asn_DEF_AllInclusive_tags_1[0]), /* 1 */
	asn_DEF_AllInclusive_tags_1,	/* Same as above */
	sizeof(asn_DEF_AllInclusive_tags_1)
		/sizeof(asn_DEF_AllInclusive_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AllInclusive_1,
	237,	/* Elements count */
	&asn_SPC_AllInclusive_specs_1	/* Additional specs */
};

