/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "CommonSafetyRequest.h"

static int
memb_requests_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_requests_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_RequestedItem,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_requests_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_requests_specs_5 = {
	sizeof(struct CommonSafetyRequest__requests),
	offsetof(struct CommonSafetyRequest__requests, _asn_ctx),
	1,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requests_5 = {
	"requests",
	"requests",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_requests_tags_5,
	sizeof(asn_DEF_requests_tags_5)
		/sizeof(asn_DEF_requests_tags_5[0]) - 1, /* 1 */
	asn_DEF_requests_tags_5,	/* Same as above */
	sizeof(asn_DEF_requests_tags_5)
		/sizeof(asn_DEF_requests_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_requests_5,
	1,	/* Single element */
	&asn_SPC_requests_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CommonSafetyRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CommonSafetyRequest, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_POINTER, 2, offsetof(struct CommonSafetyRequest, msgCnt),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgCnt"
		},
	{ ATF_POINTER, 1, offsetof(struct CommonSafetyRequest, id),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CommonSafetyRequest, requests),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_requests_5,
		memb_requests_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requests"
		},
};
static ber_tlv_tag_t asn_DEF_CommonSafetyRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CommonSafetyRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID at 112 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* msgCnt at 113 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* id at 114 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* requests at 117 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CommonSafetyRequest_specs_1 = {
	sizeof(struct CommonSafetyRequest),
	offsetof(struct CommonSafetyRequest, _asn_ctx),
	asn_MAP_CommonSafetyRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CommonSafetyRequest = {
	"CommonSafetyRequest",
	"CommonSafetyRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CommonSafetyRequest_tags_1,
	sizeof(asn_DEF_CommonSafetyRequest_tags_1)
		/sizeof(asn_DEF_CommonSafetyRequest_tags_1[0]), /* 1 */
	asn_DEF_CommonSafetyRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_CommonSafetyRequest_tags_1)
		/sizeof(asn_DEF_CommonSafetyRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CommonSafetyRequest_1,
	4,	/* Elements count */
	&asn_SPC_CommonSafetyRequest_specs_1	/* Additional specs */
};

