/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "RainSensor.h"

int
RainSensor_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
RainSensor_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

void
RainSensor_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
RainSensor_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
RainSensor_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
RainSensor_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
RainSensor_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
RainSensor_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RainSensor_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_RainSensor_value2enum_1[] = {
	{ 0,	4,	"none" },
	{ 1,	9,	"lightMist" },
	{ 2,	9,	"heavyMist" },
	{ 3,	18,	"lightRainOrDrizzle" },
	{ 4,	4,	"rain" },
	{ 5,	12,	"moderateRain" },
	{ 6,	9,	"heavyRain" },
	{ 7,	13,	"heavyDownpour" }
};
static unsigned int asn_MAP_RainSensor_enum2value_1[] = {
	7,	/* heavyDownpour(7) */
	2,	/* heavyMist(2) */
	6,	/* heavyRain(6) */
	1,	/* lightMist(1) */
	3,	/* lightRainOrDrizzle(3) */
	5,	/* moderateRain(5) */
	0,	/* none(0) */
	4	/* rain(4) */
};
static asn_INTEGER_specifics_t asn_SPC_RainSensor_specs_1 = {
	asn_MAP_RainSensor_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RainSensor_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_RainSensor_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RainSensor = {
	"RainSensor",
	"RainSensor",
	RainSensor_free,
	RainSensor_print,
	RainSensor_constraint,
	RainSensor_decode_ber,
	RainSensor_encode_der,
	RainSensor_decode_xer,
	RainSensor_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RainSensor_tags_1,
	sizeof(asn_DEF_RainSensor_tags_1)
		/sizeof(asn_DEF_RainSensor_tags_1[0]), /* 1 */
	asn_DEF_RainSensor_tags_1,	/* Same as above */
	sizeof(asn_DEF_RainSensor_tags_1)
		/sizeof(asn_DEF_RainSensor_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RainSensor_specs_1	/* Additional specs */
};

