/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "RequestedItem.h"

int
RequestedItem_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
RequestedItem_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

void
RequestedItem_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
RequestedItem_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
RequestedItem_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
RequestedItem_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
RequestedItem_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
RequestedItem_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RequestedItem_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_RequestedItem_value2enum_1[] = {
	{ 0,	8,	"reserved" },
	{ 1,	5,	"itemA" },
	{ 2,	5,	"itemB" },
	{ 3,	5,	"itemC" },
	{ 4,	5,	"itemD" },
	{ 5,	5,	"itemE" },
	{ 6,	5,	"itemF" },
	{ 7,	5,	"itemG" },
	{ 8,	5,	"itemH" },
	{ 9,	5,	"itemI" },
	{ 10,	5,	"itemJ" },
	{ 11,	5,	"itemK" },
	{ 12,	5,	"itemL" },
	{ 13,	5,	"itemM" },
	{ 14,	5,	"itemN" },
	{ 15,	5,	"itemO" },
	{ 16,	5,	"itemP" },
	{ 17,	5,	"itemQ" }
	/* This list is extensible */
};
static unsigned int asn_MAP_RequestedItem_enum2value_1[] = {
	1,	/* itemA(1) */
	2,	/* itemB(2) */
	3,	/* itemC(3) */
	4,	/* itemD(4) */
	5,	/* itemE(5) */
	6,	/* itemF(6) */
	7,	/* itemG(7) */
	8,	/* itemH(8) */
	9,	/* itemI(9) */
	10,	/* itemJ(10) */
	11,	/* itemK(11) */
	12,	/* itemL(12) */
	13,	/* itemM(13) */
	14,	/* itemN(14) */
	15,	/* itemO(15) */
	16,	/* itemP(16) */
	17,	/* itemQ(17) */
	0	/* reserved(0) */
	/* This list is extensible */
};
static asn_INTEGER_specifics_t asn_SPC_RequestedItem_specs_1 = {
	asn_MAP_RequestedItem_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RequestedItem_enum2value_1,	/* N => "tag"; sorted by N */
	18,	/* Number of elements in the maps */
	19,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_RequestedItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RequestedItem = {
	"RequestedItem",
	"RequestedItem",
	RequestedItem_free,
	RequestedItem_print,
	RequestedItem_constraint,
	RequestedItem_decode_ber,
	RequestedItem_encode_der,
	RequestedItem_decode_xer,
	RequestedItem_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RequestedItem_tags_1,
	sizeof(asn_DEF_RequestedItem_tags_1)
		/sizeof(asn_DEF_RequestedItem_tags_1[0]), /* 1 */
	asn_DEF_RequestedItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_RequestedItem_tags_1)
		/sizeof(asn_DEF_RequestedItem_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RequestedItem_specs_1	/* Additional specs */
};

