/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "TravelerInformation.h"

static int
memb_dataFrames_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_dataFrames_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DataFrame,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_dataFrames_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_dataFrames_specs_6 = {
	sizeof(struct TravelerInformation__dataFrames),
	offsetof(struct TravelerInformation__dataFrames, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dataFrames_6 = {
	"dataFrames",
	"dataFrames",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_dataFrames_tags_6,
	sizeof(asn_DEF_dataFrames_tags_6)
		/sizeof(asn_DEF_dataFrames_tags_6[0]) - 1, /* 1 */
	asn_DEF_dataFrames_tags_6,	/* Same as above */
	sizeof(asn_DEF_dataFrames_tags_6)
		/sizeof(asn_DEF_dataFrames_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_dataFrames_6,
	1,	/* Single element */
	&asn_SPC_dataFrames_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TravelerInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TravelerInformation, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_POINTER, 3, offsetof(struct TravelerInformation, packetID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniqueMSGID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packetID"
		},
	{ ATF_POINTER, 2, offsetof(struct TravelerInformation, urlB),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URL_Base,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"urlB"
		},
	{ ATF_POINTER, 1, offsetof(struct TravelerInformation, dataFrameCount),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Count,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataFrameCount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TravelerInformation, dataFrames),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_dataFrames_6,
		memb_dataFrames_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataFrames"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TravelerInformation, crc),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCRC,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"crc"
		},
};
static ber_tlv_tag_t asn_DEF_TravelerInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TravelerInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID at 431 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* packetID at 432 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* urlB at 433 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dataFrameCount at 434 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dataFrames at 436 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* crc at 437 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TravelerInformation_specs_1 = {
	sizeof(struct TravelerInformation),
	offsetof(struct TravelerInformation, _asn_ctx),
	asn_MAP_TravelerInformation_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TravelerInformation = {
	"TravelerInformation",
	"TravelerInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TravelerInformation_tags_1,
	sizeof(asn_DEF_TravelerInformation_tags_1)
		/sizeof(asn_DEF_TravelerInformation_tags_1[0]), /* 1 */
	asn_DEF_TravelerInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_TravelerInformation_tags_1)
		/sizeof(asn_DEF_TravelerInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TravelerInformation_1,
	6,	/* Elements count */
	&asn_SPC_TravelerInformation_specs_1	/* Additional specs */
};

