# Makefile for California PATH shared code
#
# Copyright (c) 2008   Regents of the University of California
#

include $(CAPATH_MK_DEFS)

all: $(wildcard src/*.[ch]) 
	(cd src; make)
clean:
	(cd src; make clean)
