include $(CAPATH_MK_DEFS)

# Location of files common to all projects under long_ctl/src
COMMON_DIR = ../../common
TRUCKDIR = /home/truckcontrol
JBUS_DIR = $(TRUCKDIR)/j1939/src
VEHCOMM_DIR = $(TRUCKDIR)/long_ctl/src/vehcomm
AVCS_DIR = $(TRUCKDIR)/long_ctl/src/avcs
XYL_DIR = $(TRUCKDIR)/long_ctl/src/xyl
LIDAR_DIR = /home/path/sens/lidar/mdl

CFLAGS = $(PATH_CFLAGS) -I$(COMMON_DIR) -I$(JBUS_DIR) -DPROTOTYPE
CFLAGS += -I$(VEHCOMM_DIR) -I$(AVCS_DIR) -I$(LIDAR_DIR) -I$(XYL_DIR)

LINK = $(PATH_LINK)
LINKFLAGS = $(PATH_LDFLAGS) -L$(COMMON_DIR) -L. -L$(JBUS_DIR)/$(OBJDIR)
LIBS = -llong_utils -ljbus -ltrack $(PATH_LIBS) 

TRACKLIB = libtrack.a

#
# User Defined macros for files, directories, etc.

OTHER_SRCS = acc_flt.c \
             brk_flt.c \
             cntract.c \
             control.c \
             coording.c \
             dvi.c \
             emap_525.c \
             eng_map.c \
             filt_1.c \
             filt_2.c \
             filt_4.c \
             fuel_flt.c \
             gear_tbl.c \
             gen_ref.c \
             jk_map.c \
             mag_dist.c \
             maneuver.c \
             pich_flt.c \
             pm_filt.c \
             ptch_flt.c \
             rad_dist.c \
             ref_dist.c \
             ref_ini.c \
             sig_flt1.c \
             sig_flt2.c \
             sinsat.c \
             smooth.c \
             spd_flt.c \
             svg13.c \
             svg25.c \
             svg31.c \
             svg3a.c \
             svg3b.c \
             svg3c.c \
             svg3.c \
             svg5.c \
             svg73.c \
             tran_ref.c \
             usyn_flt.c \
             v_flt.c \
             mdl_flt.c \
             vrd_flt.c 

OTHER_OBJS = $(OTHER_SRCS:c=o)

#
# Default rules
#

all:   $(OTHER_OBJS) $(TRACKLIB)

.c.o:
	$(CC) $(CFLAGS) -o $@ $<

$(TRACKLIB): $(OTHER_OBJS)
	$(PATH_AR) $(PATH_AR_FLAGS) $@ $(OTHER_OBJS)

#
# Object file dependencies
#

long_ctl.o:	$(COMMON_DIR)/long_ctl.c $(COMMON_DIR)/long_ctl.h
	$(CC) $(CFLAGS) -o $@ $<

$(LONG_CTL_OBJS):	$(COMMON_DIR)/long_ctl.h track.h veh_long.h coording.h long_trk.h

#
# Distribution control rules
#

install:  all
	cp -f $(TRACKLIB) $(XYL_DIR)

clean:
	/bin/rm -f *.o \
	*.err \
	$(TRACKLIB)

distclean: clean
	cd $(DISTRIB_DIR)/long_ctl/test; /bin/rm -f cmdtest

