#ifndef _VAA_CLT_VARS_H 
#define _VAA_CLT_VARS_H

/** change this when any are added
 */
#define NUM_VAA_MSG_IDS	15

#define DB_VAA_BASE 1000

#define DB_SENSOR_CONFIG_ID	1
#define DB_SENSOR_STATE_ID	2
#define DB_MESSAGE_STATUS_ID	3
#define DB_POSITION_NORMAL_ID	4
#define DB_POSITION_RAW_ID	5
#define DB_POSITION_CALIBRATION_ID	6
#define DB_CC_STATUS_ID	7
#define DB_SYSTEM_COMMAND_ID	8
#define DB_DATA_INPUTS_ID	9
#define DB_HMI_STATE_ID		10
#define DB_HMI_DEVICE_STATE_ID	11
#define DB_HMI_OPTIONAL_DATA_ID	12
#define DB_CC_STATE_ID		13
#define DB_CC_OPERATION_STATE_ID	14
#define DB_CC_OPTIONAL_DATA_ID	15

#define DB_SENSOR_CONFIG_VAR	DB_VAA_BASE + DB_SENSOR_CONFIG_ID
#define DB_SENSOR_STATE_VAR	DB_VAA_BASE + DB_SENSOR_STATE_ID
#define DB_MESSAGE_STATUS_VAR	DB_VAA_BASE + DB_MESSAGE_STATUS_ID
#define DB_POSITION_NORMAL_VAR	DB_VAA_BASE + DB_POSITION_NORMAL_ID
#define DB_POSITION_RAW	_VAR	DB_VAA_BASE + DB_POSITION_RAW_ID
#define DB_POSITION_CALIBRATION_VAR	DB_VAA_BASE + DB_POSITION_CALIBRATION_ID
#define DB_CTRL_COM_STATUS_VAR	DB_VAA_BASE + DB_CTRL_COM_STATUS_ID
#define DB_SYSTEM_COMMAND_VAR	DB_VAA_BASE + DB_SYSTEM_COMMAND_ID
#define DB_DATA_INPUTS_VAR		DB_VAA_BASE + DB_DATA_INPUTS_ID
#define DB_HMI_STATE_VAR		DB_VAA_BASE + DB_HMI_STATE_ID
#define DB_HMI_DEVICE_STATE_VAR	DB_VAA_BASE + DB_HMI_DEVICE_STATE_ID
#define DB_HMI_OPTIONAL_DATA_VAR	DB_VAA_BASE + DB_HMI_OPTIONAL_DATA_ID
#define DB_CC_STATE_VAR		DB_VAA_BASE + DB_CC_STATE_ID
#define DB_CC_OPERATION_STATE_VAR	DB_VAA_BASE + DB_CC_OPERATION_STATE_ID
#define DB_CC_OPTIONAL_DATA_VAR	DB_VAA_BASE + DB_CC_OPTIONAL_DATA_ID

#endif
