# Makefile - PATH GPS library and sample programs
#
# Copyright (c) 2008   Regents of the University of California
#

include $(CAPATH_MK_DEFS)

all: 
	(cd src; make; make install)
	(cd examples; make)

clean:
	(cd src; make clean)
	(cd examples; make clean)
