/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735BSMESSAGE"
 * 	found in "BasicSafetyMessage-Volvo.txt"
 */

#include "BSMCACC.h"

static asn_TYPE_member_t asn_MBR_BSMCACC_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BSMCACC, msgID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DSRCmsgID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msgID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BSMCACC, blob1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSMblob,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"blob1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BSMCACC, caccData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CaccData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caccData"
		},
};
static ber_tlv_tag_t asn_DEF_BSMCACC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BSMCACC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* blob1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* caccData */
};
static asn_SEQUENCE_specifics_t asn_SPC_BSMCACC_specs_1 = {
	sizeof(struct BSMCACC),
	offsetof(struct BSMCACC, _asn_ctx),
	asn_MAP_BSMCACC_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BSMCACC = {
	"BSMCACC",
	"BSMCACC",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BSMCACC_tags_1,
	sizeof(asn_DEF_BSMCACC_tags_1)
		/sizeof(asn_DEF_BSMCACC_tags_1[0]), /* 1 */
	asn_DEF_BSMCACC_tags_1,	/* Same as above */
	sizeof(asn_DEF_BSMCACC_tags_1)
		/sizeof(asn_DEF_BSMCACC_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BSMCACC_1,
	3,	/* Elements count */
	&asn_SPC_BSMCACC_specs_1	/* Additional specs */
};

